# Generated by Django 4.1.7 on 2023-05-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="degree",
            field=models.CharField(
                default="Boshqarma Boshlig'ning \nBirinchi o'rin bosari", max_length=50
            ),
        ),
    ]
