# Generated by Django 4.1.7 on 2023-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="degree",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
