# Generated by Django 4.1.7 on 2023-05-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.CharField(
                choices=[("owner", "Owner"), ("staff", "Staff")],
                default="staff",
                max_length=10,
            ),
        ),
    ]
