# Generated by Django 4.1.7 on 2023-05-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="degree",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(
                blank=True, default=1, max_length=150, verbose_name="last name"
            ),
            preserve_default=False,
        ),
    ]
