# Generated by Django 4.1.7 on 2023-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_account_degree_alter_account_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Birinchi o'rin boasr", "First"),
                    ("Ikkinchi o\rin boasr", "Second"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
