# Generated by Django 4.1.7 on 2023-05-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipimagePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipfile", models.FileField(upload_to="")),
            ],
        ),
    ]
