# Generated by Django 4.1.7 on 2023-05-31 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepart",
            name="imagefile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imageparts",
                to="images_files.imagefile",
            ),
        ),
    ]
