# Generated by Django 4.1.7 on 2023-05-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0003_alter_imagepart_oneimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepart",
            name="oneimage",
            field=models.FileField(upload_to="oneimage"),
        ),
    ]
