# Generated by Django 4.1.7 on 2023-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0007_alter_imagepart_oneimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepart",
            name="oneimage",
            field=models.FileField(blank=True, null=True, upload_to="oneimage"),
        ),
    ]
