# Generated by Django 4.1.7 on 2023-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0008_alter_imagepart_oneimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepart",
            name="imagefile",
            field=models.FileField(blank=True, null=True, upload_to="imagefile"),
        ),
    ]
