# Generated by Django 4.1.7 on 2023-04-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0009_alter_imagepart_imagefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagepart",
            name="imagefile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imageparts",
                to="images_files.imagefile",
            ),
        ),
    ]
