# Generated by Django 4.1.7 on 2023-04-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0010_alter_imagepart_imagefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagepart",
            name="qrcode_image",
        ),
    ]
