# Generated by Django 4.1.7 on 2023-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images_files", "0011_remove_imagepart_qrcode_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="image_pdf",
            field=models.FileField(unique=True, upload_to="images_pdf"),
        ),
    ]
